### ISSUE TITLE
Hacking_Windows_ALPHA.pdf errors

### ISSUE THREAD

**Issue by HadManySons** [mytechnotalent/Hacking-Windows#1]
On page 5, "We also use the stdcall Win32 callign" calling misspelled.

On page 5 it says, "Our first Win32API that we will call is the ExitProcess which simply exits the application and frees up the operation to the Windows OS." But that is the second function called, MessageBoxA is the first.

On page 6, "The first param is HWND hWnd which is a handle to the owner of the window of the message box to be created and in our case it is NULL meaning the message bhas has no owner." "has" or "box has" misspelled.

**Comment by mytechnotalent** [comment]
Thank you so kindly @HadManySons I will make these revisions during the next lessons release.

**Comment by mytechnotalent** [comment]
Just pushed revision 2.
